### ISSUE TITLE
I want to collaborate with midi2ffxiv.conf

### ISSUE THREAD

**Issue by Noutyr** [m13253/midi2ffxiv#4]
This isn't actually an issue, sorry if it bothers anyone, I will delete it if needed (and if I can)
I made a conf that works for spanish speakers on latin american keyboard (It has the "¿" symbol)
https://pastebin.com/8Hu5mCJz

It goes with this configuration in-game
https://i.imgur.com/9uRVCAh.png

  | C | D | E | F | G | A | B | C+1
-- | -- | -- | -- | -- | -- | -- | -- | --
High | A | D | G | H | K | ' | - | +
Mid | Q | W | E | R | T | Y | U |  
Low | Z | C | B | N | , | 0 | ¿ |  
  |   |   |   |   |   |   |   |  
  | C | Eb | F# | G# | Bb |   |   |  
High | S | F | J | L | { |   |   |  
Mid | 2 | 3 | 5 | 6 | 7 |   |   |  
Low | X | V | M | . | < |   |   |  

I made it for a friend that has a bard and want to link his piano with the game, I thought that it would be useful for other people too and is worth to share it.

**Comment by m13253** [comment]
Thank you for your contribution!

I put your configuration file at [contrib/spanish.conf](https://github.com/m13253/midi2ffxiv/blob/master/contrib/spanish.conf).

Please check it.

**Comment by Noutyr** [comment]
Thanks you for let me collaborate! I checked it and is alright.
